### ISSUE TITLE
No carga la información si hay un retraso desde la web de Solidmation

### ISSUE THREAD

**Issue by JMVS** [mool/home-assistant-bgh-smart#2]
Hola,

En el día de hoy me apareció esto:
![imagen](https://user-images.githubusercontent.com/7751148/86781512-62677080-c034-11ea-9a62-6b3310da6245.png)

Con este error en el registro de Home Assistant:
```
Home Assistant 0.112.3

Logger: homeassistant.components.websocket_api.http.connection.140318281651600
Source: custom_components/bgh_smart/climate.py:184
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:19:26 (4 occurrences)
Last logged: 9:19:35

'unknown'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 430, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bgh_smart/climate.py", line 202, in set_hvac_mode
    self.set_mode()
  File "/config/custom_components/bgh_smart/climate.py", line 184, in set_mode
    self._fan_speed)
  File "/usr/local/lib/python3.7/site-packages/pybgh/__init__.py", line 142, in set_mode
    'fanMode': FAN_MODE[fan],
KeyError: 'unknown'
```

Atribuyo este problema cuando el servidor de Solidmation demora demasiado en dar una respuesta. Lo mismo pasa en la aplicación Smart Control, donde figuran todos los equipos con estado "desconocido" para luego reportar el estado correcto (con una demora aproximada de 40-60 segundos).

**Comment by JMVS** [comment]
Estoy viendo que la interfaz web the Solidmation figura todo en 0 tal como figura en esta integración:
![imagen](https://user-images.githubusercontent.com/7751148/86821497-dae42680-c060-11ea-8055-05f9dff6cfc5.png)

Pero en la aplicación desde el teléfono (Android en este caso, si figura la información y funciona). ¿Será que habrá una forma de comunicación distinta entre la aplicación y la web?

**Comment by mool** [comment]
Lamentablemente el servicio de solidmation anda MUY mal, cada tanto pasa que deja de responder y les toma días arreglarlo.

**Comment by mool** [comment]
Acabo de mergear un cambio que arregla este error cuando la API de Solidmation no esta funcionando.

**Comment by lucasedgardo** [comment]
Una consulta, donde consiguieron la documentación para poder config la api en home assistant?
Tengo dos BGH Smart Control Kit y no logro encontrar la forma de integrarlos

**Comment by JMVS** [comment]
> Una consulta, donde consiguieron la documentación para poder config la api en home assistant? Tengo dos BGH Smart Control Kit y no logro encontrar la forma de integrarlos

Esta toda la info en la pagina principal de este complemento: https://github.com/mool/home-assistant-bgh-smart
Se puede hacer de manera manual o a traves de HACS: https://hacs.xyz/ agregando este repositorio

**Comment by lucasedgardo** [comment]
Genial.
Voy a intentar nuevamente porque no logré que se conecte al servidor.

Gracias por la ayuda !

**Comment by lucasedgardo** [comment]
Hola,
Molesto de nuevo en este post porque quizás sepan algo.
La app de BGH ya no se puede instalar en android. O al menos de momento. Tiene una falla y se desinstaló sola, y al intentar volver a instalarla da un error.
Por lo que vi la API de la integración sigue funcionando sin problema, incluso al entrar desde la web de bgh sigue enviando datos y recibiendo de los dispositivos.
El problema es que tengo que agregar dos equipos nuevos y sin la App no logro sincronizarlos.
Descargué MyHabeetat de Solidmation y logré que los mismos equipos de BGH funcionen con esta app pero obviamente cada app tiene sus equipos que fueron sincronizados con cada una de ellas. El tema es que las que están en MyHabeetat no puedo subrilas a Hassio.
Alguna idea? Tuvieron problemas similares? Hoy siguen viendo la APP en el Tel? Voy intentar con Iphone para ver si el problema es el mismo.
Gracias
