### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by JMVS** [mool/home-assistant-bgh-smart#4]
Quería avisar que Home Assistant está arrojando un nuevo error en la integración debido a un nuevo cambio: 

No 'version' key in the manifest file for custom integration 'bgh_smart'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'bgh_smart'

Ver más info acá: https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by mool** [comment]
Esto quedo solucionado hace un tiempo. Saludos!
