### ISSUE TITLE
Could not connect to BGH Smart cloud

### ISSUE THREAD

**Issue by postar** [mool/home-assistant-bgh-smart#7]
Buenas Tardes Mool
Primero q nada gracias por la integracion
Estoy teniendo problemas en home assistant me da el siguiente error

This error originated from a custom integration.

Logger: custom_components.bgh_smart.climate
Source: custom_components/bgh_smart/climate.py:67
Integration: bgh_smart (documentation)
First occurred: 2:29:00 PM (1 occurrences)
Last logged: 2:29:00 PM

Could not connect to BGH Smart cloud

**Comment by JMVS** [comment]
Ese mensaje se debe probablemente a que no pudo obtener el token al intentar iniciar en el servicio de BGH. Se me ocurre que esto podría deberse a tres cosas: un error en los datos de ingreso (usuario/contraseña); lo imposibilidad de llegar a los servidores de BGH (problemas de conexión a Internet, firewall, etc) o, que efectivamente el servicio de BGH haya estado caído.

**Comment by postar** [comment]
Lo estuve chequeando y nunca se me creó la cuenta en la pagina de bgh por eso no funcionaba, utilicé una cuenta anterior que si tenia el login en la pagina y salio funcionando.
Perdon por hacerte perder el tiempo y gracias!!
